// imageLookup.js
const imageLookup = {
    arpeggio: require('../assets/capsules/arpeggio.png'),
    buenosaires: require('../assets/capsules/buenosaires.png'),
    cafezinho: require('../assets/capsules/cafezinho.png'),
    capeTown: require('../assets/capsules/capeTown.png'),
    capriccio: require('../assets/capsules/capriccio.png'),
    caramel: require('../assets/capsules/caramel.png'),
    chiaro: require('../assets/capsules/chiaro.png'),
    colombia: require('../assets/capsules/colombia.png'),
    corto: require('../assets/capsules/corto.png'),
    cosi: require('../assets/capsules/cosi.png'),
    ethiopia: require('../assets/capsules/ethiopia.png'),
    firenze: require('../assets/capsules/firenze.png'),
    firenzeDecaf: require('../assets/capsules/firenzeDecaf.png'),
    genova: require('../assets/capsules/genova.png'),
    india: require('../assets/capsules/india.png'),
    indonesia: require('../assets/capsules/indonesia.png'),
    miami: require('../assets/capsules/miami.jpg'),
    millennio: require('../assets/capsules/millennio.png'),
    napoli: require('../assets/capsules/napoli.png'),
    nicaragua: require('../assets/capsules/nicaragua.png'),
    peru: require('../assets/capsules/peru.png'),
    ristretto: require('../assets/capsules/ristretto.png'),
    roma: require('../assets/capsules/roma.png'),
    scuro: require('../assets/capsules/scuro.png'),
    shanghai: require('../assets/capsules/shanghai.png'),
    stockholm: require('../assets/capsules/stockholm.png'),
    tokyo: require('../assets/capsules/tokyo.png'),
    uganda: require('../assets/capsules/uganda.png'),
    vanilla: require('../assets/capsules/vanilla.png'),
    venezia: require('../assets/capsules/venezia.png'),
    volluto: require('../assets/capsules/volluto.png'),
    vollutoDecaf: require('../assets/capsules/vollutoDecaf.png'),
  };
  
  export default imageLookup;
  